# PRINT ALL PERMUTATIONS OF A STRING
# APPROACH 1 (BACKTRACKING METHOD):
# CHOOSE ONE CHARACTER
# ADD IT TO CURRENT PATH
# RECURSIVELY GENERATE PERMUTATIONS
# OF REMAINING CHARACTERS
# REPEAT UNTIL NO CHARACTERS REMAIN
# STORE COMPLETE PERMUTATION
# TIME COMPLEXITY:
# O(N × N!)
# SPACE COMPLEXITY:
# O(N)
# INTERVIEW VALUE:
# MOST COMMONLY ASKED
# EASY TO EXPLAIN
# STANDARD RECURSION TEMPLATE
# APPROACH 2 (SWAP BACKTRACKING METHOD):
# FIX CURRENT POSITION
# SWAP CURRENT CHARACTER
# WITH REMAINING CHARACTERS
# RECURSIVELY SOLVE
# FOR NEXT POSITION
# SWAP BACK TO RESTORE STATE
# TIME COMPLEXITY:
# O(N!)
# SPACE COMPLEXITY:
# O(N)
# INTERVIEW VALUE:
# BEST INTERVIEW SOLUTION
# IN-PLACE MODIFICATION
# MEMORY EFFICIENT
# OPTIMIZED BACKTRACKING
# APPROACH 3 (ITERTOOLS METHOD):
# USE BUILT-IN PERMUTATIONS()
# GENERATE ALL POSSIBLE
# CHARACTER ARRANGEMENTS
# CONVERT TUPLES TO STRINGS
# STORE OR PRINT RESULT
# TIME COMPLEXITY:
# O(N!)
# SPACE COMPLEXITY:
# O(N!)
# INTERVIEW VALUE:
# PYTHON BUILT-IN
# FASTEST TO WRITE
# NOT PREFERRED AS MAIN INTERVIEW SOLUTION
# EDGE CASES:
# EMPTY STRING
# SINGLE CHARACTER
# DUPLICATE CHARACTERS
# ALL SAME CHARACTERS
# SPECIAL CHARACTERS
# LARGE STRING
# KEY OBSERVATION:
# EACH CHARACTER CAN OCCUPY
# EVERY POSITION
# TOTAL PERMUTATIONS:
# N!
# INTERVIEW COMPARISON:
# BACKTRACKING METHOD:
# EASY TO UNDERSTAND
# EASY TO IMPLEMENT
# MOST EXPECTED
# SWAP BACKTRACKING METHOD:
# BEST OVERALL SOLUTION
# OPTIMAL RECURSIVE APPROACH
# FREQUENTLY PREFERRED
# ITERTOOLS METHOD:
# BEST FOR REAL PROJECTS
# NOT FOR DSA INTERVIEWS
# CONCLUSION:
# BEGINNER FRIENDLY:
# BACKTRACKING METHOD
# INTERVIEW EXPECTED:
# BACKTRACKING METHOD
# BEST INTERVIEW SOLUTION:
# SWAP BACKTRACKING METHOD
# PYTHON BUILT-IN:
# ITERTOOLS.PERMUTATIONS()

#USING BACKTRACKING METHOD
def permutations(s):
    result=[]
    def backtrack(path,remaining):
        if len(remaining)==0:
            result.append(path)
            return
        for i in range(len(remaining)):
            backtrack(path+remaining[i],remaining[:i]+remaining[i+1:])
    backtrack("",s)
    return result
print(permutations("ABC"))


#SWAP BACKTRACKING METHOD
def permutations(s):
    chars=list(s)
    result=[]
    def backtrack(index):
        if index==len(chars):
            result.append("".join(chars))
            return
        for i in range(index,len(chars)):
            chars[index],chars[i]=chars[i],chars[index]
            backtrack(index+1)
            chars[index],chars[i]=chars[i],chars[index]
    backtrack(0)
    return result
print(permutations("ABC"))

#USING ITERTOOLS METHOD
from itertools import permutations
for p in permutations("ABC"):
    print("".join(p))