# NUMBER TO WORD (UP TO 999)
# PROBLEM
# CONVERT A NUMBER INTO ITS ENGLISH WORD REPRESENTATION
# RANGE: 0 TO 999
# EXAMPLES
# 0   → ZERO
# 7   → SEVEN
# 25  → TWENTY FIVE
# 123 → ONE HUNDRED TWENTY THREE
# 999 → NINE HUNDRED NINETY NINE
# APPROACH 1 (LIST METHOD)
# STORE WORDS FOR:
# 1-9   IN ones LIST
# 10-19 IN teens LIST
# 20-90 IN tens LIST
# EXTRACT HUNDREDS, TENS, AND ONES DIGITS
# BUILD THE FINAL WORD STEP BY STEP
# TIME COMPLEXITY: O(1)
# SPACE COMPLEXITY: O(1)
# INTERVIEW VALUE: MOST COMMON
# APPROACH 2 (FUNCTION-BASED METHOD)
# CREATE SEPARATE FUNCTIONS FOR:
# ONE DIGIT
# TWO DIGITS
# THREE DIGITS
# COMBINE RESULTS
# TIME COMPLEXITY: O(1)
# SPACE COMPLEXITY: O(1)
# INTERVIEW VALUE: CLEAN CODE
# APPROACH 3 (DICTIONARY METHOD)
# STORE NUMBER-WORD MAPPINGS IN DICTIONARY
# LOOKUP WORDS USING KEYS
# TIME COMPLEXITY: O(1)
# SPACE COMPLEXITY: O(1)
# INTERVIEW VALUE: GOOD FOR MAPPING PROBLEMS
# APPROACH 4 (RECURSIVE METHOD)
# BREAK NUMBER INTO SMALLER PARTS
# RECURSIVELY CONVERT REMAINING DIGITS
# TIME COMPLEXITY: O(1)
# SPACE COMPLEXITY: O(1)
# INTERVIEW VALUE: RECURSION PRACTICE
# APPROACH 5 (BUILT-IN LIBRARY METHOD
# USE num2words PACKAGE
# EXAMPLE:
# from num2words import num2words
# print(num2words(123))
# TIME COMPLEXITY: O(1)
# SPACE COMPLEXITY: O(1)
# INTERVIEW VALUE: NOT PREFERRED
# CORE LOGIC
# n // 100 → HUNDREDS DIGIT
# n % 100  → REMAINING PART
# n // 10  → TENS DIGIT
# n % 10   → ONES DIGIT
# SPECIAL CASE
# 10 TO 19 HAVE UNIQUE WORDS
# USE teens LIST
# EDGE CASES
# 0   → ZERO
# 1   → ONE
# 9   → NINE
# 10  → TEN
# 15  → FIFTEEN
# 20  → TWENTY
# 21  → TWENTY ONE
# 99  → NINETY NINE
# 100 → ONE HUNDRED
# 101 → ONE HUNDRED ONE
# 110 → ONE HUNDRED TEN
# 115 → ONE HUNDRED FIFTEEN
# 999 → NINE HUNDRED NINETY NINE
# FORMULA / DIGIT EXTRACTION
# HUNDREDS = n // 100
# REMAINING = n % 100
# TENS = n // 10
# ONES = n % 10
# CONCLUSION
# BEST APPROACH: LIST METHOD
# BEST TIME COMPLEXITY: O(1)
# BEST SPACE COMPLEXITY: O(1)
# MOST ASKED IN INTERVIEWS FOR BASIC STRING AND NUMBER MANIPULATION

#USING LISTS METHOD
ones = ["", "One", "Two", "Three", "Four", "Five",
        "Six", "Seven", "Eight", "Nine"]

teens = ["Ten", "Eleven", "Twelve", "Thirteen", "Fourteen",
         "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"]

tens = ["", "", "Twenty", "Thirty", "Forty",
        "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"]
def number_words(n):
    if n==0:
        return "ZERO"
    result=""
    if n>=100:
        result+=ones[n//100]+"Hundred"
        n%=100
    if 10<=n<=19:
        result+=teens[n-10]
    else:
        result+=tens[n//10]
        if n%10:
            result+=""+ones[n%10]
    return result.strip()
n=int(input())
print(number_words(n))

