# SIMPLE INTEREST AND COMPOUND INTEREST
# APPROACH 1 (DIRECT FORMULA METHOD):
# CALCULATE SIMPLE INTEREST USING SI FORMULA
# CALCULATE COMPOUND INTEREST USING CI FORMULA
# RETURN BOTH VALUES
# SIMPLE INTEREST FORMULA:
# SI = (P * R * T) / 100
# COMPOUND INTEREST FORMULA:
# CI = P(1 + R/100)^T - P
# TIME COMPLEXITY:
# O(1)
# SPACE COMPLEXITY:
# O(1)
# INTERVIEW VALUE:
# MOST EXPECTED SOLUTION
# SIMPLE AND EFFICIENT
# APPROACH 2 (USER INPUT METHOD):
# TAKE PRINCIPAL FROM USER
# TAKE RATE FROM USER
# TAKE TIME FROM USER
# CALCULATE SI
# CALCULATE CI
# DISPLAY RESULTS
# TIME COMPLEXITY:
# O(1)
# SPACE COMPLEXITY:
# O(1)
# INTERVIEW VALUE:
# GOOD FOR BEGINNERS
# COMMON IN BASIC PROGRAMMING QUESTIONS
# APPROACH 3 (BUILT-IN POW() METHOD):
# USE POW() FUNCTION
# TO CALCULATE EXPONENTIAL PART
# OF COMPOUND INTEREST FORMULA
# CALCULATE SI NORMALLY
# CALCULATE CI USING POW()
# TIME COMPLEXITY:
# O(1)
# SPACE COMPLEXITY:
# O(1)
# INTERVIEW VALUE:
# SHOWS KNOWLEDGE OF BUILT-IN FUNCTIONS
# CLEANER IMPLEMENTATION
# EDGE CASES:
# PRINCIPAL = 0
# RATE = 0
# TIME = 0
# NEGATIVE VALUES
# DECIMAL VALUES
# LARGE VALUES
# KEY OBSERVATION:
# SIMPLE INTEREST:
# INTEREST IS CALCULATED ONLY ON PRINCIPAL
# COMPOUND INTEREST:
# INTEREST IS CALCULATED ON PRINCIPAL + PREVIOUS INTEREST
# INTERVIEW COMPARISON:
# DIRECT FORMULA METHOD:
# BEST OVERALL SOLUTION
# MOST EXPECTED
# USER INPUT METHOD:
# GOOD FOR BASIC PROGRAMS
# POW() METHOD:
# CLEANER IMPLEMENTATION
# USES BUILT-IN FUNCTION
# CONCLUSION:
# INTERVIEW EXPECTED:
# DIRECT FORMULA METHOD
# BEST TIME COMPLEXITY:
# O(1)
# BEST SPACE COMPLEXITY:
# O(1)
# PYTHON BUILT-IN:
# POW()

#USING DIRECT FORMULA METHOD
def calculate_interest(principal,rate,time):
    simple_interest=(principal*rate*time)/100
    compound_interest=principal*((1+rate/100)**time)-principal
    return simple_interest,compound_interest
si,ci=calculate_interest(1000,5,2)
print("SIMPLE INTEREST",si)
print("COMPOUND INTEREST",ci)

#USING SUER INPUT METHOD
principal = float(input("Enter Principal: "))
rate = float(input("Enter Rate: "))
time = float(input("Enter Time: "))
si = (principal * rate * time) / 100
ci = principal * ((1 + rate / 100) ** time) - principal
print("Simple Interest =", si)
print("Compound Interest =", ci)

#SUING POW() METHOD
def calculate_interest(principal,rate,time):
    si=(principal*rate*time)/100
    ci=principal*pow((1+rate/100),time)-principal
    return si,ci
si,ci=calculate_interest(1000,5,2)
print("SI",si)
print("CI",ci)