#SUM OF ARRAY ELEMENTS USING RECURSION
#CORE IDEA:
#ADD CURRENT ELEMENT
#AND RECURSIVELY ADD
#THE REMAINING ELEMENTS
#EDGE CASES:
#EMPTY ARRAY
#SINGLE ELEMENT
#ALL POSITIVE NUMBERS
#ALL NEGATIVE NUMBERS
#ARRAY WITH ZEROS
#LARGE ARRAY
#EXAMPLE:
#ARR=[1,2,3,4,5]
#OUTPUT=15
#APPROACH 1(INDEX RECURSION):
#START FROM INDEX 0
#ADD CURRENT ELEMENT
#MOVE TO NEXT INDEX
#BASE CASE:
#INDEX==LEN(ARR)
#RETURN 0
#RECURSIVE CASE:
#ARR[INDEX]+RECURSIVE CALL
#APPROACH 2(SLICING RECURSION):
#TAKE FIRST ELEMENT
#ADD SUM OF REMAINING ARRAY
#BASE CASE:
#LEN(ARR)==0
#RETURN 0
#RECURSIVE CASE:
#ARR[0]+RECURSIVE CALL
#APPROACH 3(DIVIDE AND CONQUER):
#DIVIDE ARRAY INTO TWO HALVES
#SUM LEFT HALF
#SUM RIGHT HALF
#ADD BOTH RESULTS
#BASE CASE:
#LEFT>RIGHT RETURN 0
#LEFT==RIGHT RETURN ARR[LEFT]
#RECURSIVE CASE:
#LEFT SUM + RIGHT SUM
#TIME COMPLEXITY:
#INDEX RECURSION->O(N)
#SLICING RECURSION->O(N²)
#DIVIDE AND CONQUER->O(N)
#SPACE COMPLEXITY:
#INDEX RECURSION->O(N)
#SLICING RECURSION->O(N)
#DIVIDE AND CONQUER->O(LOGN)
#BETTER SOLUTION:
#INDEX RECURSION
#OPTIMAL SOLUTION:
#INDEX RECURSION
#ADVANCED SOLUTION:
#DIVIDE AND CONQUER
#MOST INTERVIEWERS EXPECT:
#INDEX RECURSION

#SUM OF ARRAY ELEMENTS
def sum_array(arr,index=0):
    #BASE CASE 
    if index<0:
        return 0
    if index==len(arr):
        return 0
    return arr[index] + sum_array(arr,index+1)
print(sum_array([1,2,3,4,5]))


#SLICING RECURSION
def sum_array(arr):
    #BASE CASE
    if len(arr)==0:
        return 0
    #FIRST ELEMENT + REMAINING SUM
    return arr[0]+sum_array(arr[1:])
print(sum_array([1,2,3,4,5]))

#DIVIDE AND CONQUER METHOD
def sum_array(arr,left,right):
    #BASE CASE
    if left>right:
        return 0
    if left==right:
        return arr[left]
    mid=(left+right)//2
    left_sum=sum_array(arr,left,mid)
    right_sum=sum_array(arr,mid+1,right)
    return left_sum+right_sum
arr=[1,2,3,4,5]
print(sum_array(arr,0,len(arr)-1))
