#CHECK STRINGS ARE ROTATION OF EACH OTHER
#TO DETERMINE WHETHER ONE STRING CAN BE OBTAINED BY ROTATING ANOTHER STRING 
#TWO STRINGS ARE ROTATION EACH OTHER IF:
      #THEIR LENGTHS ARE EQUAL
      #ONE STRING APPEARS INSIDE THE DOUBLE VERSION OF ANOTHER STRING
      #EX :"ABCD"->"ABCDABCD"->INSIDE IT ->CDAB
      #HENCE CDAB IS A ROTATION OF ABCD
#EDGE CASE:
           #IDENTICAL STRINGS->0 ROTATIONS->TRUE
           #SINGLE CHARACTER -> TRUE
           #DIFFERENT CHARACTERS ->FALSE
           #FOR "" AND ""->TRUE CONSIDER HAS ROTATIONS
           #SAME CHARACTER ORDER IS DIFFERENT -> FALSE
           #NO ROTATION HAPPENS WHEN ORDER IF DIFFERENT
#TWO STRINGS ARE ROTATIONS OF EACH OTHER IF THEY HAVE THE SAME 
#LENGTH AND ONE STRING APPEARS INSIDE THE DOUBLED VERSION OF THE OTHER STRING,
#BECAUSE EVERY POSSIBLE ROTATION IS AUTOMATICALLY PRESENT IN THE DOUBLED STRING.

#BRUTE FORCE APPROACH
def rotation(s1,s2):
    #EDGE CASE:
    if len(s1)!=len(s2):
        return False
    n=len(s1)
    for i in range(n):
        rotation=s1[i:]+s1[:i]
        if rotation==s2:
            return True
    return False
print(rotation("ABCD","CDAB"))

#OPTIMAL DOUBLE STRING METHOD
def rotation(s1,s2):
    #EDGE CASE:
        if len(s1)!=len(s2):
            return False
        return s2 in (s1+s1)
print(rotation("ABCD","CDAB"))