#CHECK PALINDROME USING RECURSION
#CORE IDEA:
#CHECK WHETHER STRING READS
#SAME FORWARD AND BACKWARD
#EDGE CASES:
#EMPTY STRING
#SINGLE CHARACTER
#EVEN LENGTH STRING
#ODD LENGTH STRING
#PALINDROME STRING
#NON PALINDROME STRING
#EXAMPLE:
#INPUT="MADAM"
#OUTPUT=True
#APPROACH 1(TWO POINTER RECURSION):
#COMPARE FIRST AND LAST CHARACTER
#MOVE INWARDS
#BASE CASE:
#LEFT>=RIGHT
#RETURN TRUE
#RECURSIVE CASE:
#IF CHARACTERS MATCH
#CHECK INNER STRING
#APPROACH 2(SLICING RECURSION):
#COMPARE FIRST AND LAST CHARACTER
#RECURSE ON MIDDLE PART
#BASE CASE:
#LEN(S)<=1
#RETURN TRUE
#RECURSIVE CASE:
#CHECK S[1:-1]
#APPROACH 3(REVERSE STRING RECURSION):
#REVERSE STRING
#COMPARE WITH ORIGINAL STRING
#BASE CASE:
#LEN(S)==0
#RETURN ""
#RECURSIVE CASE:
#REVERSE(S[1:])+S[0]
#TIME COMPLEXITY:
#TWO POINTER->O(N)
#SLICING->O(N²)
#REVERSE STRING->O(N²)
#SPACE COMPLEXITY:
#TWO POINTER->O(N)
#SLICING->O(N)
#REVERSE STRING->O(N)
#BEST SOLUTION:
#TWO POINTER RECURSION
#OPTIMAL SOLUTION:
#TWO POINTER RECURSION
#EASIEST SOLUTION:
#SLICING RECURSION
#MOST INTERVIEWERS EXPECT:
#TWO POINTER RECURSION

#CHECK PALINDROME USING RECURSION
def is_palindrome(s,left,right):
    #BASE CASE
    if left>=right:
        return True
    #CHARACTERS NOT MATCHING 
    if s[left]!=s[right]:
        return False
    #RECURSIVE CALL 
    return is_palindrome(s,left+1,right-1)
s="MADAM"
print(is_palindrome(s,0,len(s)-1))


#USING SLICING RECURSION METHOD
def is_palindrome(s):
    #BASE CASE
    if len(s)<=1:
        return True
    if s[0]!=s[-1]:
        return False
    return is_palindrome(s[1:-1])
print(is_palindrome("MADAM"))

#REVERSE STRING RECURSION
def reverse_string(s):
    #BASE CASE
    if len(s)==0:
        return ""
    return reverse_string(s[1:])+s[0]
def is_palindrome(s):
    return s==reverse_string(s)
print(is_palindrome("MADAM"))